### ISSUE TITLE
Erro ao gerar QR Code

### ISSUE THREAD

**Issue by whamulti** [ldurans/izing.open.io#110]
Estou fazendo a instalação pelo aaPanel, usando a versão do "whatsapp-web.js": "^1.19.4"

O painel fica tentando se conectar mesmo sem um QR Code scaneado e não gera novos QRs

![Captura de tela 2023-02-12 115553](https://user-images.githubusercontent.com/116593038/218318970-bb3ac015-5565-45f8-a529-bd3a22ed2308.png)

![Captura de tela 2023-02-12 115814](https://user-images.githubusercontent.com/116593038/218318979-75255f6b-2beb-4319-8ab5-2a8b8162afa9.png)

error: 2023-02-12T14:58:21.465Z ERROR: checkMessages Tenant: 1:: Cannot read property 'evaluate' of null - TypeError: Cannot read property 'evaluate' of null
    at Client.getState (/www/wwwroot/gomes/backend/node_modules/whatsapp-web.js/src/Client.js:845:35)
    at /www/wwwroot/gomes/backend/dist/libs/wbot.js:91:53
    at Generator.next (<anonymous>)
    at /www/wwwroot/gomes/backend/dist/libs/wbot.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/www/wwwroot/gomes/backend/dist/libs/wbot.js:4:12)
    at Timeout.checkMessages [as _onTimeout] (/www/wwwroot/gomes/backend/dist/libs/wbot.js:89:43)
    at listOnTimeout (internal/timers.js:559:11)
    at processTimers (internal/timers.js:500:7)

**Comment by JrZavaschi** [comment]
cd backend
npm i whatsapp-web.js --save
pm2 restart all
