### ISSUE TITLE
Não envia áudio pelo pc

### ISSUE THREAD

**Issue by fehveiga** [ldurans/izing.open.io#124]
Olá pessoal, tudo bem? 
estou a alguns dias sofrendo com alguns bugs…
Tenho um vps com ubuntu 20.04, aapanel, pm2 com Node 14.21.1, postgresql, redis, rabbitmq, nginx1.21.
Foi triste de compilar até que descobri todos os macetes haha agora não descobri como concertar o erro websocket (a conversão só atualiza com F5), clica no microfone e não acontece nada além da permissão (no celular funciona) e queria saber se é possível adicionar ver a conversa sem aceitar.

obrigado desde já

**Comment by fehveiga** [comment]
Problema de não atualizar resolvido.
Já o problema de não acontecer nada ao clicar no microfone do pc, nada ainda...

Percebi agora que quando tento iniciar uma "campanha" ele não cancela mais, não edita.. enfim...

Error: 
    <p class="text-bold">
      Ops...<br>
      <span class="text-bold">Só é permitido programar campanhas que estejam pendentes ou canceladas.</span>
    </p>
    <p>Detail: </p>
    
    at o.re [as $notificarErro] (app.05f34881.js?__WB_REVISION__=fad41f1e2ef2597a0d856f8b288f9055:1:25671)
    at o.iniciarCampanha (7.f6a8963c.js?__WB_REVISION__=39916727ff06672b6b7057900280cee3:1:18698)
    at click (7.f6a8963c.js?__WB_REVISION__=39916727ff06672b6b7057900280cee3:1:1777)
    at Gt (vendor.5ab43e44.js:21:20571)
    at o.n (vendor.5ab43e44.js:21:10795)
    at Gt (vendor.5ab43e44.js:21:20571)
    at Sn.e.$emit (vendor.5ab43e44.js:21:25603)
    at o.__navigateOnClick (vendor.5ab43e44.js:86:108428)
    at o.click (vendor.5ab43e44.js:88:24439)
    at Gt (vendor.5ab43e44.js:21:20571)


Se alguem souber de algo

**Comment by fehveiga** [comment]
app.3f7adc40.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'error')
    at o.re [as $notificarErro] (app.3f7adc40.js:1:25214)
    at 7.8c9aabdb.js:1:18326
re @ app.3f7adc40.js:1
(anonymous) @ 7.8c9aabdb.js:1
Promise.catch (async)
(anonymous) @ 7.8c9aabdb.js:1
(anonymous) @ vendor.6cffae28.js:48
ok @ vendor.6cffae28.js:48
Gt @ vendor.6cffae28.js:21
n @ vendor.6cffae28.js:21
Gt @ vendor.6cffae28.js:21
Sn.e.$emit @ vendor.6cffae28.js:21
onOk @ vendor.6cffae28.js:48
Gt @ vendor.6cffae28.js:21
n @ vendor.6cffae28.js:21
Gt @ vendor.6cffae28.js:21
Sn.e.$emit @ vendor.6cffae28.js:21
__navigateOnClick @ vendor.6cffae28.js:86
click @ vendor.6cffae28.js:88
Gt @ vendor.6cffae28.js:21
n @ vendor.6cffae28.js:21
Aa.a._wrapper @ vendor.6cffae28.js:21

**Comment by like-brands** [comment]
Para enviar áudio é necessário ter SSL configurado.
