### ISSUE TITLE
Erro após ler o QR Code do WhatsApp

### ISSUE THREAD

**Issue by erickne** [ldurans/izing.open.io#189]
1. Executei a instalação via docker
2. Rodei o migration e seed
3. Loguei como admin
4. Ao criar um novo canal com whatsapp, o QR Code é gerado e retorna o erro abaixo no log do backend

Estou usando a última versão 2.0.1

```
2024-05-01 08:28:56 info: 2024-05-01T11:28:56.819Z joinChatServer USER Administrador
2024-05-01 08:29:00 info: 2024-05-01T11:29:00.008Z SendMessageSchenduled Initiated
2024-05-01 08:29:00 info: 2024-05-01T11:29:00.022Z Finalized SendMessageSchenduled
2024-05-01 08:29:29 info: 2024-05-01T11:29:29.300Z Session QR CODE: era-ID: 2-OPENING
2024-05-01 08:29:45 info: 2024-05-01T11:29:45.882Z Session QR CODE: era-ID: 2-OPENING
2024-05-01 08:30:00 info: 2024-05-01T11:30:00.011Z SendMessageSchenduled Initiated
2024-05-01 08:30:00 info: 2024-05-01T11:30:00.019Z FindUpdateTicketsInactiveChatBot Initiated
2024-05-01 08:30:00 info: 2024-05-01T11:30:00.073Z Finalized SendMessageSchenduled
2024-05-01 08:30:00 info: 2024-05-01T11:30:00.074Z Finalized FindUpdateTicketsInactiveChatBot
2024-05-01 08:30:09 error: 2024-05-01T11:30:09.307Z Cannot read properties of undefined (reading 'toString') - TypeError: Cannot read properties of undefined (reading 'toString')
2024-05-01 08:30:09     at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/puppeteer-core/src/common/ExecutionContext.ts:253:37)
2024-05-01 08:30:09     at ExecutionContext.evaluate (/app/node_modules/puppeteer-core/src/common/ExecutionContext.ts:137:32)
2024-05-01 08:30:09     at IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/src/common/IsolatedWorld.ts:224:20)
2024-05-01 08:30:09     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-01 08:30:09 Error: Cannot set headers after they are sent to the client
2024-05-01 08:30:09     at new NodeError (node:internal/errors:405:5)
2024-05-01 08:30:09     at ServerResponse.setHeader (node:_http_outgoing:648:11)
2024-05-01 08:30:09     at ServerResponse.header (/app/node_modules/express/lib/response.js:795:10)
2024-05-01 08:30:09     at ServerResponse.send (/app/node_modules/express/lib/response.js:175:12)
2024-05-01 08:30:09     at ServerResponse.json (/app/node_modules/express/lib/response.js:279:15)
2024-05-01 08:30:09     at /app/src/app/modules.ts:55:28
2024-05-01 08:30:09     at Generator.next (<anonymous>)
2024-05-01 08:30:09     at /app/dist/app/modules.js:31:71
2024-05-01 08:30:09     at new Promise (<anonymous>)
2024-05-01 08:30:09     at __awaiter (/app/dist/app/modules.js:27:12)
2024-05-01 08:30:09     at /app/src/app/modules.ts:44:78
2024-05-01 08:30:09     at newFn (/app/node_modules/express-async-errors/index.js:16:20)
2024-05-01 08:30:09     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
2024-05-01 08:30:09     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
2024-05-01 08:30:09     at /app/node_modules/express/lib/router/index.js:286:9
2024-05-01 08:30:09     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
2024-05-01 08:30:09     at next (/app/node_modules/express/lib/router/index.js:280:10)
2024-05-01 08:30:09     at /app/node_modules/@sentry/node/src/handlers.ts:343:9
2024-05-01 08:30:09     at Hub.withScope (/app/node_modules/@sentry/hub/src/hub.ts:118:7)
2024-05-01 08:30:09     at callOnHub (/app/node_modules/@sentry/minimal/src/index.ts:25:37)
2024-05-01 08:30:09     at Object.withScope (/app/node_modules/@sentry/minimal/src/index.ts:175:3)
2024-05-01 08:30:09     at sentryErrorMiddleware (/app/node_modules/@sentry/node/src/handlers.ts:333:7)
2024-05-01 08:30:09     at newFn (/app/node_modules/express-async-errors/index.js:16:20)
2024-05-01 08:30:09     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
2024-05-01 08:30:09     at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)
2024-05-01 08:30:09     at /app/node_modules/express/lib/router/index.js:286:9
2024-05-01 08:30:09     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
2024-05-01 08:30:09     at Domain.next (/app/node_modules/express/lib/router/index.js:280:10)
2024-05-01 08:30:09     at Domain.emit (node:events:517:28)
2024-05-01 08:30:09     at Domain.emit (node:domain:489:12)
2024-05-01 08:30:09     at emit (node:internal/process/promises:147:33)
2024-05-01 08:30:09     at processPromiseRejections (node:internal/process/promises:283:27)
2024-05-01 08:30:09     at processTicksAndRejections (node:internal/process/task_queues:96:32)
```

**Comment by estefanio** [comment]
Testa Essa solução

cd izing/backend (pasta onde ta instalado o izing)

npm r whatsapp-web.js

npm i whatsapp-web.js 
 
pm2 start 0
