### ISSUE TITLE
Problema nos Multíplos usuários simultâneos por canais de atendimento

### ISSUE THREAD

**Issue by XNINGUEMX** [ldurans/izing.open.io#198]
Boa tarde.

Estou tentando acessar o Izing com usuários criados no painel do administrador, porem quando coloco email e senha criada para um usuário e tento acessar pelo ip:8080 em outra maquina na mesma rede carrega a barra azul mas não acessa o aplicativo, no backend não da erro nos logs, eu fiz também ate uma conexão via túnel com cloudflare + registro.br mesmo assim deu o mesmo problema, acredito que não estou conseguindo estabelecer uma conexão de entrada somente saída esta funcionando pois consigo acessar a pagina de login, mas não consigo logar. 
Alguém tem alguma dica para ajudar?

**Comment by rownaas** [comment]
Opa amigo, verificou se apareceu alguma coisa dentro do console do navegador ao fazer a requisição de login?
As vezes pode ser por conta do cors, dai você precisa instalar uma extensão no navegador chamada cors unblock, quando ativa ela resolve este problema, além disto pode ser algum erro de rota do frontend pra api/backend

**Comment by XNINGUEMX** [comment]
O amigo muito obrigado pela dica a principio agora consigo acessar no mesmo PC usando cors unblock com host ip e tunel, porem quando vou logar, em outro PC mesmo tendo também a extenção cors unblock não loga no console do Chorme da esses erros aqui. mesmo assim muito obrigado pela dica ^^ vou continuar tentando resolver esse probleminha se siter mais uma saida por onde devo estudar eu agradeço ^^



       Failed to load resource: net::ERR_CONNECTION_REFUSED
websocket.js:87 WebSocket connection to 'ws://localhost:3100/socket.io/?EIO=4&transport=websocket' failed: 
doOpen @ websocket.js:87
Mostrar mais 1 frame
Mostre menos
socket.js:21 socket error Error: websocket error
    at WS.onError (transport.js:29:1)
    at ws.onerror (websocket.js:116:1)
(anónimo) @ socket.js:21
websocket.js:87 WebSocket connection to 'ws://localhost:3100/socket.io/?EIO=4&transport=websocket' failed: 
doOpen @ websocket.js:87
Mostrar mais 1 frame
Mostre menos
websocket.js:87 WebSocket connection to 'ws://localhost:3100/socket.io/?EIO=4&transport=websocket' failed: 
doOpen @ websocket.js:87
Mostrar mais 1 frame
Mostre menos
socket.js:21 socket error Error: websocket error
    at WS.onError (transport.js:29:1)
    at ws.onerror (websocket.js:116:1)
(anónimo) @ socket.js:21
push../node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
(anónimo) @ manager.js:127
push../node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
onError @ socket.js:594
(anónimo) @ socket.js:213
push../node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
onError @ transport.js:32
ws.onerror @ websocket.js:116
Mostrar mais 8 frames
Mostre menos
websocket.js:87 WebSocket connection to 'ws://localhost:3100/socket.io/?EIO=4&transport=websocket' failed: 
doOpen @ websocket.js:87
open @ transport.js:44
open @ socket.js:183
Socket @ socket.js:107
push../node_modules/engine.io-client/lib/index.js.module.exports @ index.js:3
open @ manager.js:112
(anónimo) @ manager.js:339
Mostrar mais 7 frames
Mostre menos
websocket.js:87 WebSocket connection to 'ws://localhost:3100/socket.io/?EIO=4&transport=websocket' failed: 
doOpen @ websocket.js:87
open @ transport.js:44
open @ socket.js:183
Socket @ socket.js:107
push../node_modules/engine.io-client/lib/index.js.module.exports @ index.js:3
open @ manager.js:112
(anónimo) @ manager.js:339
Mostrar mais 7 frames
Mostre menos
socket.js:21 socket error Error: websocket error
    at WS.onError (transport.js:29:1)
    at ws.onerror (websocket.js:116:1)
