### ISSUE TITLE
Conexão com WhatsApp

### ISSUE THREAD

**Issue by SrElric** [ldurans/izing.open.io#202]
Problema com conexão do WhatsApp, gera o QR code mas não está conectando, tentei atualizar o WEB..JS e até mesmo a aplicação por inteiro porém mesmo assim não está funcionando

**Comment by alissondavid09** [comment]
aqui ocorreu mesmo problema, parece que houve uma atualização de ontem pra hoje

**Comment by rownaas** [comment]
Também deu a mesma coisa para mim hoje, fiquei horas para resolver, mas acabei rebuildando o backend e criei novos canais para os celulares antigos, e vinculei novamente e deu certo, tive que reiniciar algumas vezes... No final só alterei o id dos celulares dentro do banco de dados da tabela de tickets e resolveu

**Comment by ricfrenov** [comment]
Boa noite Pessoal, estou tendo esse erro no backend na geração do QR Code sem falar que quando gera o qr code não consigo ler, o node deve ser a versão 20 mesmo?

Erro:
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:659:11)
    at ServerResponse.header (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\response.js:795:10)
    at ServerResponse.send (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\response.js:175:12)
    at ServerResponse.json (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\response.js:279:15)
    at C:\Users\ricfr\WhatsApp\izing.open.io\backend\dist\app\modules.js:88:36
    at Generator.next (<anonymous>)
    at C:\Users\ricfr\WhatsApp\izing.open.io\backend\dist\app\modules.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ricfr\WhatsApp\izing.open.io\backend\dist\app\modules.js:27:12)
    at C:\Users\ricfr\WhatsApp\izing.open.io\backend\dist\app\modules.js:77:39
    at newFn (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle_error (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:326:13)
    at C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:280:10)
    at C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\@sentry\node\dist\handlers.js:201:17
    at Hub.withScope (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\@sentry\hub\dist\hub.js:88:13)
    at callOnHub (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\@sentry\minimal\dist\index.js:18:28)
    at Object.withScope (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\@sentry\minimal\dist\index.js:163:5)
    at sentryErrorMiddleware (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\@sentry\node\dist\handlers.js:191:20)
    at newFn (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle_error (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:326:13)
    at C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:346:12)
    at Domain.next (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:280:10)
    at Domain.emit (node:events:519:28)
info: 2024-08-17T22:25:00.026Z FindUpdateTicketsInactiveChatBot Initiated
info: 2024-08-17T22:25:00.028Z SendMessageSchenduled Initiated
info: 2024-08-17T22:25:00.036Z Finalized FindUpdateTicketsInactiveChatBot
info: 2024-08-17T22:25:00.038Z Finalized SendMessageSchenduled
