### ISSUE TITLE
Erro salvar Contato

### ISSUE THREAD

**Issue by fabriciosprj** [ldurans/izing.open.io#227]
Ocorreu um erro ao válidar o contato pelo whatsapp..

Verifique se a conexão com o whatsapp está ativa. Se necessário, atualize a página e tente novamente em alguns instantes.

**Comment by fabriciosprj** [comment]
p class="text-bold">
      <span class="text-bold">Ocorreu um erro ao válidar o contato pelo whatsapp..</span>
      </p>
      <p>Verifique se a conexão com o whatsapp está ativa. Se necessário, atualize a página e tente novamente em alguns instantes.</p>
    
    at s.ce [as $notificarErro] (app.75bc243f.js:1:26686)
    at s.saveContact (chunk-common.14821dbc.js:1:4683)
